export default function Loader() {
  return (
    <div className=" inline-block relative w-20 h-20 ">
      <div className=" [animation-delay:-0.036s] after:top-[63px] after:left-[63px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.072s] after:top-[68px] after:left-[56px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.108s] after:top-[71px] after:left-[48px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.144s] after:top-[72px] after:left-[40px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.18s] after:top-[71px] after:left-[32px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.216s] after:top-[68px] after:left-[24px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.252s] after:top-[63px] after:left-[17px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
      <div className=" [animation-delay:-0.288s] after:top-[56px] after:left-[12px] after:content-[' '] after:block after:bg-[#aeb4b7] after:rounded-[50%] after:absolute after:w-[7px] after:h-[7px] after:mt-[-4px] after:mr-0 after:mb-0 after:ml-[-4px] animate-[ldsroller_1.2s_cubic-bezier(0.5,0,0.5,1)_infinite] origin-[40px_40px]"></div>
    </div>
  )
}
